### ISSUE TITLE
Exception thrown: 'System.ArgumentException' in Npgsql.EntityFrameworkCore.PostgreSQL.dll

### ISSUE THREAD

**Issue by eightsixeight** [larry-oj/DotNetConverter#1]
Hi this need a sql backend ? Can we get the configuration and setup for this?

Seems that it bombs with 

Exception thrown: 'System.ArgumentException' in Npgsql.EntityFrameworkCore.PostgreSQL.dll
An exception of type 'System.ArgumentException' occurred in Npgsql.EntityFrameworkCore.PostgreSQL.dll but was not handled in user code
The string argument 'connectionString' cannot be empty.

**Comment by eightsixeight** [comment]
yes all fixed, however , you need to upgrade both youtubeexplode and youtubeexplode.converter to get rid of the errors ,

**Comment by larry-oj** [comment]
yeah, i already open an issue, will fix it soon!
10 minutes is a default value, and can be changed in `appsettings.json`, you can modify it for your needs! i've set 10 minutes as a good time threshold so files don't stuck up too much and don't take up too much space in cloud its running on.
